/*
R-3.1 Give the next five pseudorandom numbers generated by the process described on
page 113, with a = 12, b = 5, and n = 100, and 92 as the seed for cur

next = (a ∗ cur + b) % n
a = 12
b = 5
n = 100
cur = 92


 */

